### ISSUE TITLE
Exception on import python3.9

### ISSUE THREAD

**Issue by esquire900** [deepgram/python-sdk#7]
## What is the current behavior?
`from deepgram import Deepgram` results in an exception

TypeError: unhashable type: 'list'
Most relevant lines:
```
File ".../python3.9/site-packages/deepgram/_types.py", line 171, in <module>
    EventHandler = Union[Callable[[Any], None], Callable[[Any], Awaitable[None]]]
```

## Steps to reproduce
Python3.9, pip install, from deepgram import Deepgram

## Please tell us about your environment

> We want to make sure the problem isn't specific to your operating system or programming language.
Ubuntu 21.04

## Other information

Is solved by changing
`EventHandler = Union[Callable[[Any], None], Callable[[Any], Awaitable[None]]]`
into
`EventHandler = Union[Callable[Any, None], Callable[Any, Awaitable[None]]]`

in deepgram/_types.py

Full trace:
Traceback (most recent call last):
  File "/home/script/tmi_archive/manage.py", line 22, in <module>
    main()
  File "/home/script/tmi_archive/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/simon/.local/share/virtualenvs/tmi_archive-Ytjv44Ey/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/simon/.local/share/virtualenvs/tmi_archive-Ytjv44Ey/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/simon/.local/share/virtualenvs/tmi_archive-Ytjv44Ey/lib/python3.9/site-packages/django/core/management/__init__.py", line 263, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/simon/.local/share/virtualenvs/tmi_archive-Ytjv44Ey/lib/python3.9/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/opt/anaconda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/script/tmi_archive/talks/management/commands/transcribe-deepgram.py", line 2, in <module>
    from deepgram import Deepgram
  File "/home/simon/.local/share/virtualenvs/tmi_archive-Ytjv44Ey/lib/python3.9/site-packages/deepgram/__init__.py", line 2, in <module>
    from ._types import Options
  File "/home/simon/.local/share/virtualenvs/tmi_archive-Ytjv44Ey/lib/python3.9/site-packages/deepgram/_types.py", line 171, in <module>
    EventHandler = Union[Callable[[Any], None], Callable[[Any], Awaitable[None]]]
  File "/home/opt/anaconda/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/home/opt/anaconda/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/home/opt/anaconda/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/home/opt/anaconda/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'

**Comment by frumsdotxyz** [comment]
I'm unable to reproduce this on my install - the docs for `Callable` (and Pylance linting) imply that [the argument types should always either be a list or `...`](https://docs.python.org/3/library/typing.html#typing.Callable).
Could you possibly provide your `conda list` / `pip list` output?

**Comment by esquire900** [comment]
This issue was very persistent previously, but I can't replicate it anymore. Apologies, you are correct.
